Feat/mongo db ds
RevealBi/Reveal.Sdk.Dom pull request #104
Opened 2024-11-28 14:49 UTC by hainv-ohio

2024-12-03 17:28 UTC, brianlagunas commented
# DO NOT MERGE

Since we have not been able to create a working visualization with this connector, it's not ready for merging. I will review and see if I can figure out why it's not working.

2024-12-07 00:28 UTC, brianlagunas commented
This still needs to be rebased with the main branch

2024-12-10 18:36 UTC, brianlagunas commented
this still has merge conflicts

2024-12-10 18:44 UTC, brianlagunas requested changes
fix merge conflcits

2024-12-12 21:42 UTC, brianlagunas requested changes

2024-12-13 03:40 UTC, hainv-ohio commented on src/Reveal.Sdk.Dom/Data/DataSources/MongoDBDataSource.cs
> +    public class MongoDBDataSource : DataSource
It was a mistake when I tried to make it work, I misunderstood some things, one of them I undertood `Database` field wasn't needed. Reverted

2024-12-17 17:40 UTC, brianlagunas reviewed
fix the merge conflicts

2024-12-17 17:40 UTC, brianlagunas commented
never mind, I'll do it

2024-12-17 17:42 UTC, merged