Create unit tests for IValuesExtensions
RevealBi/Reveal.Sdk.Dom pull request #158
Opened 2024-12-19 10:38 UTC by vulh-infragistics

2024-12-23 09:26 UTC, hainv-ohio requested changes

2024-12-23 09:26 UTC, hainv-ohio commented on src/Reveal.Sdk.Dom.Tests/Visualizations/Extensions/IValuesExtensionsFixture.cs
> +        public void SetValue_AddValuesItem_WithListNumberFields()
Should be `SetValues`

2024-12-23 09:26 UTC, hainv-ohio commented on src/Reveal.Sdk.Dom.Tests/Visualizations/Extensions/IValuesExtensionsFixture.cs
> +        public void SetValue_AddValuesItem_WithListFieldNames()
should be `SetValues`

2024-12-26 06:43 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/Extensions/IValuesExtensionsFixture.cs
> +        public void SetValue_AddValuesItem_WithListNumberFields()
Updated

2024-12-26 07:21 UTC, hainv-ohio approved these changes

2024-12-26 07:21 UTC, merged