add tests for single visualization base
RevealBi/Reveal.Sdk.Dom pull request #193
Opened 2024-12-25 14:38 UTC by hainv-ohio

2024-12-27 09:37 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/SingleValueLabelsVisualizationBaseFixture.cs
> +        public void VisualizationDataSpec_GetSetAsExpected_WhenUse(String type)
Update UT name

2024-12-27 09:38 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/SingleValueLabelsVisualizationBaseFixture.cs
> +        public void VisualizationDataSpec_GetSetAsExpected_WhenUse(String type)
Not sure if it's needed as this field only has default getter and setter.

2024-12-27 09:39 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/SingleValueLabelsVisualizationBaseFixture.cs
> +            Assert.Equal(visSpec.Rows, labels);
I think we only need the final Assertions `Assert.Equal(visSpec.Rows, labels);`, as this includes other assertions

2024-12-27 09:42 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/SingleValueLabelsVisualizationBaseFixture.cs
> +            Assert.Empty(labels);
Assert.Empty already includes Assert.NotNull

2024-12-27 09:45 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/SingleValueLabelsVisualizationBaseFixture.cs
> +            Assert.Equal(visSpec.Value, values);
Assert.Equal(visSpec.Value, values); already covers 2 assertion above

2024-12-27 09:56 UTC, vulh-infragistics requested changes
Please update the comments

2024-12-29 23:31 UTC, recca5p requested changes

2024-12-29 23:31 UTC, recca5p commented on src/Reveal.Sdk.Dom.Tests/Visualizations/SingleValueLabelsVisualizationBaseFixture.cs
> +            Assert.Empty(labels);
I think we should add an assertion to verify that the returned list is not null, even if empty

2024-12-29 23:31 UTC, recca5p commented on src/Reveal.Sdk.Dom.Tests/Visualizations/SingleValueLabelsVisualizationBaseFixture.cs
> +            Assert.Empty(values);
Similar to the Labels test, add Assert.NotNull(values) to make sure that returned list is not null

2024-12-30 09:21 UTC, recca5p approved these changes

2024-12-30 15:26 UTC, vulh-infragistics approved these changes

2024-12-31 06:50 UTC, merged