Update Time Series Visualization
RevealBi/Reveal.Sdk.Dom pull request #219
Opened 2024-12-26 13:57 UTC by recca5p

2024-12-30 04:09 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/TimeSeriesVisualizationFixture.cs
> +        Assert.Equal(hasTabularData, timeSeriesVisualization.DataDefinition.DataSourceItem.HasTabularData);
Need Assertions to check type of DataDefinition

2024-12-30 04:10 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/TimeSeriesVisualizationFixture.cs
> +            Assert.Equal(expectedHasTabularData, timeSeriesVisualization.DataDefinition.DataSourceItem.HasTabularData);
Need Assertions to check type of DataDefinition

2024-12-30 04:16 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/TimeSeriesVisualizationFixture.cs
> +        Assert.Equal(dateColumn, visualization.Date);
I think we should check the case that the VisualizationDataSpec.Rows is blank, i.e, check for the case that the Date getter reuturns null

2024-12-30 15:01 UTC, vulh-infragistics requested changes

2024-12-30 15:01 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/TimeSeriesVisualizationFixture.cs
> +    public void VisualizationDataSpec_CanBeSetAndRetrieved_WhenInitialized()
Should remove this, as the VisualizationDataSpec is now not public field

2024-12-31 01:35 UTC, recca5p commented on src/Reveal.Sdk.Dom.Tests/Visualizations/TimeSeriesVisualizationFixture.cs
> +    public void Date_CanBeSetAndRetrieved_WhenInitialized()
I tried but could not though any better name :<

2025-01-02 08:19 UTC, vulh-infragistics approved these changes

2025-01-03 02:46 UTC, hainv-ohio approved these changes

2025-01-03 02:46 UTC, merged