Update Candle Stick Visualization
RevealBi/Reveal.Sdk.Dom pull request #224
Opened 2024-12-27 06:16 UTC by recca5p

2024-12-27 08:47 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +        Assert.Null(candleStickVisualization.DataDefinition);
Need to add more assertions for default values

2024-12-27 08:50 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +    {
Missing test cases for Not-null DataSourceItem

2024-12-27 08:51 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +    {
Also need tests for the case if dataSourceItem.HasTabularData = true / false

2024-12-27 09:02 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +    public void ChartType_HasCorrectValue_WhenInstanceIsCreated()
Unneeded. It's tested inside the unit tests for Constructors

2024-12-27 09:03 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +    public void DataDefinition_CanBeUpdated_WhenNewDataSourceItemIsSet()
Remove, it's unneeded

2024-12-27 09:03 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +        document.Visualizations.Add(new PivotVisualization("Candle Stick Visualization", excelDataSourceItem)
Check type of the visualization added, Should be CandleStickVisualization

2024-12-27 09:03 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +        //Act
Remove

2024-12-27 09:04 UTC, vulh-infragistics requested changes
Please check and update the comments for all other classes

2024-12-30 03:50 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +        Assert.Equal(hasTabularData, candleStickVisualization.DataDefinition.DataSourceItem.HasTabularData);
Need assertions to check type of DataDefinition

2024-12-30 04:06 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +        var actualStr = JsonConvert.SerializeObject(actualJson);
Quite complex if we have expected json -> Parse it -> Convert it to json again. Check it again

2024-12-30 04:06 UTC, vulh-infragistics requested changes
Please update the new comments.

2024-12-30 08:51 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +        var excelDataSourceItem = new RestDataSourceItem("Marketing Sheet")
Need to re-arrange it. Those codes should not be in // Act part

2024-12-30 08:54 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +        Assert.NotNull(candleStickVisualization);
Remove this. As the codes below already ensure that candleStickVisualization is not null

2024-12-30 08:55 UTC, vulh-infragistics requested changes

2024-12-30 08:55 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Visualizations/CandleStickVisualizationFixture.cs
> +        Assert.NotNull(candleStickVisualization);
Remove this. As the codes below already ensure that candleStickVisualization is not null

2024-12-31 13:39 UTC, hainv-ohio approved these changes

2024-12-31 13:39 UTC, merged