Unit test/data source
RevealBi/Reveal.Sdk.Dom pull request #79
Opened 2024-11-15 03:41 UTC by vulh-infragistics

2024-11-15 09:55 UTC, hainv-ohio requested changes

2024-11-18 02:12 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Data/DataSourceFixture.cs
>              var dataSource = new DataSource();
Updated

2024-11-18 02:12 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Data/DataSourceFixture.cs
>              var dataSource = new DataSource();
Updated

2024-11-18 04:36 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Data/DataSourceFixture.cs
> +        public void GetHashCode_ReturnsConsistentValue_ForTheSameDataSource()
I have added a unit test to check HashCode function generates different hash code with different paramters. 
I think the current unit test already includes the case of getting hashcode with same Id

2024-11-18 09:23 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Data/DataSourceFixture.cs
> +        public void CheckEqual_ReturnFalse_WhenComparedWithNull()
Removed

2024-11-18 09:23 UTC, vulh-infragistics commented on src/Reveal.Sdk.Dom.Tests/Data/DataSourceItemFixture.cs
>              var dataSourceItem = new DataSourceItem();
Updated

2024-11-19 08:15 UTC, hainv-ohio requested changes

2024-11-19 08:15 UTC, hainv-ohio commented on src/Reveal.Sdk.Dom.Tests/Data/DataSourceItemFixture.cs
> +        public void ValidateLeftJoinFieldName_ReturnsFieldName_WithLeftFieldName/**/(string fieldName, string expected)
Remove `/**/`

2024-11-19 15:49 UTC, hainv-ohio approved these changes

2024-11-19 15:49 UTC, merged